"""
Celery task: analyze transcript and create analysis + action_items.

Input:  meeting_id (str), transcript_id (str)
Output: {"analysis_id": str, "review_item_count": int, "flagged_count": int}
"""
from __future__ import annotations

from src.config import get_logger, get_settings
from src.db.crud.meeting_crud import (
    create_analysis_result,
    get_transcript_text,
    update_meeting_status,
)
from src.db.crud.review_crud import (
    bulk_create_review_items,
    delete_review_items_for_meeting,
)
from src.workers.celery_app import celery_app

logger = get_logger(__name__)


@celery_app.task(
    name="analyze_transcript",
    bind=True,
    max_retries=1,
    default_retry_delay=10,
    queue="default",
)
def analyze_transcript(self, meeting_id: str, transcript_id: str) -> dict:
    """Analyze transcript using GPT-4o and create review items."""
    settings = get_settings()

    try:
        update_meeting_status(meeting_id, status="analyzing")
    except Exception as exc:
        logger.error("[analyze_task] Failed to update status: %s", exc)

    transcript_text = get_transcript_text(meeting_id)
    if not transcript_text.strip():
        update_meeting_status(
            meeting_id, status="failed",
            error_message="Transcript is empty - cannot analyze."
        )
        raise ValueError("Transcript is empty - cannot analyze.")

    try:
        logger.info(
            "[analyze_task] Starting analysis for meeting %s", meeting_id
        )
        from src.services.analysis_service import analyze
        meeting_analysis = analyze(transcript_text)
    except Exception as exc:
        update_meeting_status(
            meeting_id, status="failed", error_message=str(exc)
        )
        raise self.retry(exc=exc)

    all_confidences = []
    for epic in meeting_analysis.epics:
        for task_item in epic.tasks:
            all_confidences.append(task_item.confidence)
            for sub in task_item.subtasks:
                all_confidences.append(sub.confidence)
    overall_conf = (
        sum(all_confidences) / len(all_confidences) if all_confidences else 0.0
    )

    # Delete old review items
    delete_review_items_for_meeting(meeting_id)

    review_items_data = _flatten_to_review_items(
        meeting_analysis, meeting_id, settings.confidence_low_threshold
    )

    epic_ids: list[str] = []
    task_ids: list[str] = []
    inserted: list[dict] = []
    if review_items_data:
        inserted = bulk_create_review_items(review_items_data)
        # Build epic/task ID lists in same order as first-pass flatten
        for i, item in enumerate(review_items_data):
            if item["item_type"] == "epic":
                epic_ids.append(inserted[i]["id"])
            elif item["item_type"] == "task":
                task_ids.append(inserted[i]["id"])
        # Patch parent_id for subtasks
        if epic_ids or task_ids:
            patch_parent_ids(inserted, epic_ids, task_ids)

    # Upsert analysis result
    analysis_result = create_analysis_result(
        meeting_id=meeting_id,
        analysis_json=meeting_analysis.to_dict(),
        summary=meeting_analysis.summary,
        overall_confidence=overall_conf,
    )

    flagged_count = sum(1 for i in review_items_data if i.get("is_selected"))
    update_meeting_status(meeting_id, status="draft")

    logger.info(
        "[analyze_task] Complete: analysis_id=%s items=%d flagged=%d",
        analysis_result.get("id"),
        len(review_items_data),
        flagged_count,
    )
    return {
        "analysis_id": str(analysis_result.get("id")),
        "review_item_count": len(review_items_data),
        "flagged_count": flagged_count,
    }


def _priority_str(priority_val) -> str:
    """Extract priority value as string."""
    return (
        priority_val.value
        if hasattr(priority_val, "value")
        else str(priority_val)
    )


def _sanitize_for_db(value: str | None) -> str | None:
    """
    Convert 'null' string to None to prevent PostgreSQL date parsing errors.

    Supabase SDK may serialize Python None as string "null" instead of SQL NULL,
    causing 'invalid input syntax for type date: "null"' errors.
    """
    if value is None or value == "" or value.lower() == "null":
        return None
    return value


def _flatten_to_review_items(
    analysis, meeting_id: str, low_threshold: float
) -> list[dict]:
    """
    Convert MeetingAnalysis to list of dicts for bulk insert into action_items.

    Column mapping to action_items:
      - summary       → title
      - is_flagged    → is_selected  (inverted: flagged=False → selected=True)
      - item_index    → (removed — not available in action_items schema)
      - edited_*      → (removed — edits go directly to title/assignee/deadline/priority)

    parent_id is set in a second pass after IDs are generated by the DB insert.
    """
    items: list[dict] = []

    for epic in analysis.epics:
        items.append({
            "meeting_id": meeting_id,
            "item_type": "epic",
            "title": epic.summary,
            "description": epic.description,
            "review_status": "draft",
            "is_selected": False,
        })
        for task in epic.tasks:
            items.append({
                "meeting_id": meeting_id,
                "item_type": "task",
                "parent_id": None,
                "title": task.summary,
                "assignee": task.assignee,
                "deadline": _sanitize_for_db(task.deadline),
                "priority": _priority_str(task.priority),
                "description": task.context,
                "confidence_score": task.confidence,
                "review_status": "draft",
                "is_selected": task.confidence < low_threshold,
            })
            for sub in task.subtasks:
                items.append({
                    "meeting_id": meeting_id,
                    "item_type": "subtask",
                    "parent_id": None,
                    "title": sub.summary,
                    "assignee": sub.assignee,
                    "deadline": _sanitize_for_db(sub.deadline),
                    "priority": _priority_str(sub.priority),
                    "description": sub.context,
                    "confidence_score": sub.confidence,
                    "review_status": "draft",
                    "is_selected": sub.confidence < low_threshold,
                })

    return items


def patch_parent_ids(
    inserted_items: list[dict],
    epic_ids: list[str],
    task_ids: list[str],
) -> None:
    """
    Patch parent_id of subtasks in inserted_items list in-place.

    epic_ids: DB-generated IDs for epics (same order as first pass).
    task_ids:  DB-generated IDs for tasks (same order as first pass).
    """
    epic_counter = 0
    task_counter = 0
    for item in inserted_items:
        if item.get("item_type") == "task":
            if epic_counter < len(epic_ids):
                item["parent_id"] = epic_ids[epic_counter]
            epic_counter += 1
        elif item.get("item_type") == "subtask":
            if task_counter < len(task_ids):
                item["parent_id"] = task_ids[task_counter]
            task_counter += 1
